package actions

import (

  "fmt"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "userreg/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Registration)
// DB Table: Plural (registrations)
// Resource: Plural (Registrations)
// Path: Plural (/registrations)
// View Template Folder: Plural (/templates/registrations/)

// RegistrationsResource is the resource for the Registration model
type RegistrationsResource struct{
  buffalo.Resource
}

// List gets all Registrations. This function is mapped to the path
// GET /registrations
func (v RegistrationsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  registrations := &models.Registrations{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Registrations from the DB
  if err := q.All(registrations); err != nil {
    return err
  }

  // Add the paginator to the context so it can be used in the template.
  c.Set("pagination", q.Paginator)

  return c.Render(200, r.Auto(c, registrations))
}

// Show gets the data for one Registration. This function is mapped to
// the path GET /registrations/{registration_id}
func (v RegistrationsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Registration
  registration := &models.Registration{}

  // To find the Registration the parameter registration_id is used.
  if err := tx.Find(registration, c.Param("registration_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, registration))
}

// New renders the form for creating a new Registration.
// This function is mapped to the path GET /registrations/new
func (v RegistrationsResource) New(c buffalo.Context) error {
  return c.Render(200, r.Auto(c, &models.Registration{}))
}
// Create adds a Registration to the DB. This function is mapped to the
// path POST /registrations
func (v RegistrationsResource) Create(c buffalo.Context) error {
  // Allocate an empty Registration
  registration := &models.Registration{}

  // Bind registration to the html form elements
  if err := c.Bind(registration); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(registration)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the new.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, registration))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "registration.created.success"))
  // and redirect to the registrations index page
  return c.Render(201, r.Auto(c, registration))
}

// Edit renders a edit form for a Registration. This function is
// mapped to the path GET /registrations/{registration_id}/edit
func (v RegistrationsResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Registration
  registration := &models.Registration{}

  if err := tx.Find(registration, c.Param("registration_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, registration))
}
// Update changes a Registration in the DB. This function is mapped to
// the path PUT /registrations/{registration_id}
func (v RegistrationsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Registration
  registration := &models.Registration{}

  if err := tx.Find(registration, c.Param("registration_id")); err != nil {
    return c.Error(404, err)
  }

  // Bind Registration to the html form elements
  if err := c.Bind(registration); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(registration)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the edit.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, registration))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "registration.updated.success"))
  // and redirect to the registrations index page
  return c.Render(200, r.Auto(c, registration))
}

// Destroy deletes a Registration from the DB. This function is mapped
// to the path DELETE /registrations/{registration_id}
func (v RegistrationsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Registration
  registration := &models.Registration{}

  // To find the Registration the parameter registration_id is used.
  if err := tx.Find(registration, c.Param("registration_id")); err != nil {
    return c.Error(404, err)
  }

  if err := tx.Destroy(registration); err != nil {
    return err
  }

  // If there are no errors set a flash message
  c.Flash().Add("success", T.Translate(c, "registration.destroyed.success"))
  // Redirect to the registrations index page
  return c.Render(200, r.Auto(c, registration))
}
